// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDB7HFVmBk_IZdegrIcFWC9JaL6nguSS9o',
    appId: '1:933978433592:web:6c7854b9d8e7bf10795ecd',
    messagingSenderId: '933978433592',
    projectId: 'ecommerceapp-9f328',
    authDomain: 'ecommerceapp-9f328.firebaseapp.com',
    storageBucket: 'ecommerceapp-9f328.appspot.com',
    measurementId: 'G-C9MGD6EVJM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA91uw7875AKg9sf77RHw2_N4TRdY-DYIk',
    appId: '1:933978433592:android:c210abab6c215bf1795ecd',
    messagingSenderId: '933978433592',
    projectId: 'ecommerceapp-9f328',
    storageBucket: 'ecommerceapp-9f328.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBV2GULfbHb9nUoJB9hMQgw9ctJHzXq7H4',
    appId: '1:933978433592:ios:644ebe70fe199ee0795ecd',
    messagingSenderId: '933978433592',
    projectId: 'ecommerceapp-9f328',
    storageBucket: 'ecommerceapp-9f328.appspot.com',
    iosBundleId: 'com.example.ecommerceAppe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBV2GULfbHb9nUoJB9hMQgw9ctJHzXq7H4',
    appId: '1:933978433592:ios:389b9be1c6921dca795ecd',
    messagingSenderId: '933978433592',
    projectId: 'ecommerceapp-9f328',
    storageBucket: 'ecommerceapp-9f328.appspot.com',
    iosBundleId: 'com.example.ecommerceAppe.RunnerTests',
  );
}
